/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.raven.component;

import java.awt.Color;
import model.Model_User_Account;

/**
 *
 * @author DD
 */
public class Chat_title extends javax.swing.JPanel {

    /**
     * Creates new form Chat_title
     */
    public Model_User_Account getUser() {
        return user;
    }

    private Model_User_Account user;
    
    public Chat_title() {
        initComponents();
    }
    
    public void Setusername(Model_User_Account user) {
        this.user = user;
        lbname.setText(user.getUserName());
        if (user.isStatus()) {
            Statusactive();
        } else {
            Setstatustext("Ngoại tuyến");
        }
    }
    
    public void updateUser(Model_User_Account user) {
        if (this.user == user) {
            lbname.setText(user.getUserName());
            if (user.isStatus()) {
                Statusactive();
            } else {
                Setstatustext("Ngoại tuyến");
            }
        }
    }

    public void Statusactive() {
        lbstatus.setText("Đang hoạt động");
        lbstatus.setForeground(new java.awt.Color(0, 102, 0));
    }
    
    public void Setstatustext(String text) {
        lbstatus.setText(text);
        lbstatus.setForeground(new Color(160, 160, 160));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        lbname = new javax.swing.JLabel();
        lbstatus = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLayeredPane1.setLayout(new java.awt.GridLayout(0, 1));

        lbname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbname.setForeground(new java.awt.Color(63, 63, 63));
        lbname.setText("Name");
        jLayeredPane1.add(lbname);

        lbstatus.setBackground(new java.awt.Color(0, 204, 0));
        lbstatus.setForeground(new java.awt.Color(0, 102, 0));
        lbstatus.setText("Đang hoạt động");
        jLayeredPane1.add(lbstatus);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lbname;
    private javax.swing.JLabel lbstatus;
    // End of variables declaration//GEN-END:variables
}
