/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.raven.form;

import com.raven.component.Chat_body;
import com.raven.component.Chat_bottom;
import com.raven.component.Chat_title;
import model.Model_User_Account;
import model.Model_receive_message;
import model.Model_send_message;
import net.miginfocom.swing.MigLayout;
import public_event.EventChat;
import public_event.PublicEvent;

/**
 *
 * @author DD
 */
public class Chat extends javax.swing.JPanel {

    /**
     * Creates new form Menu_Left
     */
    private Chat_title chatTitle;
    private Chat_body chatBody;
    private Chat_bottom chatBottom;

    public Chat() {
        initComponents();
        init();
    }

    private void init() {
        setLayout(new MigLayout("fillx", "0[fill]0", "0[]0[100%, fill]0[shrink 0]0"));
        chatTitle = new Chat_title();
        chatBody = new Chat_body();
        chatBottom = new Chat_bottom();
        PublicEvent.getInstance().addEventChat(new EventChat() {
            @Override
            public void sendMessage(Model_send_message data) {
                chatBody.Additemright(data);
            }

            @Override
            public void receiveMessage(Model_receive_message data) {
                if (chatTitle.getUser().getUserID() == data.getFromUserID()) {
                    chatBody.Additemleft(data);
                }
            }
        });
        add(chatTitle, "wrap");
        add(chatBody, "wrap");
        add(chatBottom, "h ::50%");
    }

    public void setUser(Model_User_Account user) {
        chatTitle.Setusername(user);
        chatBottom.setUser(user);
        chatBody.clearChat();
    }

    public void updateUser(Model_User_Account user) {
        chatTitle.updateUser(user);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chat_title1 = new com.raven.component.Chat_title();
        chatbody = new com.raven.component.Chat_body();
        chat_bottom2 = new com.raven.component.Chat_bottom();

        chatbody.setBackground(new java.awt.Color(242, 242, 242));

        setBackground(new java.awt.Color(242, 242, 242));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2106, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.component.Chat_bottom chat_bottom2;
    private com.raven.component.Chat_title chat_title1;
    private com.raven.component.Chat_body chatbody;
    // End of variables declaration//GEN-END:variables
}
